# coding: utf-8

"""
    Plataforma de Ressarcimento do Open Banking Brasil

    APIs da plataforma de Ressarcimento do Open Banking Brasil para a comunicação online com a plaforma. Através da documentação das APIs abaixo é possível realizar os devidos testes de integração.  # noqa: E501

    OpenAPI spec version: beta-0.0.1
    Contact: suporte-ressarcimento@openbankingbrasil.org.br
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.refund_api_v1_api import RefundAPIV1Api  # noqa: E501
from swagger_client.rest import ApiException


class TestRefundAPIV1Api(unittest.TestCase):
    """RefundAPIV1Api unit test stubs"""

    def setUp(self):
        self.api = RefundAPIV1Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_find_notification_by_id(self):
        """Test case for find_notification_by_id

        Operação de consulta de processos de transações  # noqa: E501
        """
        pass

    def test_healthcheck(self):
        """Test case for healthcheck

        Operação de consulta de monitoramento de processos de transações  # noqa: E501
        """
        pass

    def test_notification(self):
        """Test case for notification

        Operação de registro unitário de transação   # noqa: E501
        """
        pass

    def test_notifications(self):
        """Test case for notifications

        Operação de registro em massa de uma transação  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
