# coding: utf-8

"""
    Plataforma de Ressarcimento do Open Banking Brasil

    APIs da plataforma de Ressarcimento do Open Banking Brasil para a comunicação online com a plaforma. Através da documentação das APIs abaixo é possível realizar os devidos testes de integração.  # noqa: E501

    OpenAPI spec version: beta-0.0.1
    Contact: suporte-ressarcimento@openbankingbrasil.org.br
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.refund_process import RefundProcess  # noqa: E501
from swagger_client.rest import ApiException


class TestRefundProcess(unittest.TestCase):
    """RefundProcess unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRefundProcess(self):
        """Test RefundProcess"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.refund_process.RefundProcess()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
