/* 
 * Plataforma de Ressarcimento do Open Banking Brasil
 *
 * APIs da plataforma de Ressarcimento do Open Banking Brasil para a comunicação online com a plaforma. Através da documentação das APIs abaixo é possível realizar os devidos testes de integração.
 *
 * OpenAPI spec version: beta-0.0.1
 * Contact: suporte-ressarcimento@openbankingbrasil.org.br
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RefundNotification
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RefundNotificationTests
    {
        // TODO uncomment below to declare an instance variable for RefundNotification
        //private RefundNotification instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RefundNotification
            //instance = new RefundNotification();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RefundNotification
        /// </summary>
        [Test]
        public void RefundNotificationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RefundNotification
            //Assert.IsInstanceOfType<RefundNotification> (instance, "variable 'instance' is a RefundNotification");
        }


        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Test]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'SessionToken'
        /// </summary>
        [Test]
        public void SessionTokenTest()
        {
            // TODO unit test for the property 'SessionToken'
        }
        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Test]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }
        /// <summary>
        /// Test the property 'ReceiverId'
        /// </summary>
        [Test]
        public void ReceiverIdTest()
        {
            // TODO unit test for the property 'ReceiverId'
        }
        /// <summary>
        /// Test the property 'TransmitterId'
        /// </summary>
        [Test]
        public void TransmitterIdTest()
        {
            // TODO unit test for the property 'TransmitterId'
        }
        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Test]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }
        /// <summary>
        /// Test the property 'StatusCode'
        /// </summary>
        [Test]
        public void StatusCodeTest()
        {
            // TODO unit test for the property 'StatusCode'
        }
        /// <summary>
        /// Test the property 'PayloadSize'
        /// </summary>
        [Test]
        public void PayloadSizeTest()
        {
            // TODO unit test for the property 'PayloadSize'
        }
        /// <summary>
        /// Test the property 'ProcessTimespan'
        /// </summary>
        [Test]
        public void ProcessTimespanTest()
        {
            // TODO unit test for the property 'ProcessTimespan'
        }

    }

}
