/*
 * Plataforma de Ressarcimento do Open Banking Brasil
 * APIs da plataforma de Ressarcimento do Open Banking Brasil para a comunicação online com a plaforma. Através da documentação das APIs abaixo é possível realizar os devidos testes de integração.
 *
 * OpenAPI spec version: beta-0.0.1
 * Contact: suporte-ressarcimento@openbankingbrasil.org.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The RefundProcess model module.
 * @module model/RefundProcess
 * @version beta-0.0.1
 */
export class RefundProcess {
  /**
   * Constructs a new <code>RefundProcess</code>.
   * @alias module:model/RefundProcess
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RefundProcess</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RefundProcess} obj Optional instance to populate.
   * @return {module:model/RefundProcess} The populated <code>RefundProcess</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RefundProcess();
      if (data.hasOwnProperty('processId'))
        obj.processId = ApiClient.convertToType(data['processId'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} processId
 */
RefundProcess.prototype.processId = undefined;

/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
RefundProcess.StatusEnum = {
  /**
   * value: "PENDING"
   * @const
   */
  PENDING: "PENDING",

  /**
   * value: "IN_PROGRESS"
   * @const
   */
  IN_PROGRESS: "IN_PROGRESS",

  /**
   * value: "PROCCESSED"
   * @const
   */
  PROCCESSED: "PROCCESSED"
};
/**
 * @member {module:model/RefundProcess.StatusEnum} status
 */
RefundProcess.prototype.status = undefined;

