/*
 * Plataforma de Ressarcimento do Open Banking Brasil
 * APIs da plataforma de Ressarcimento do Open Banking Brasil para a comunicação online com a plaforma. Através da documentação das APIs abaixo é possível realizar os devidos testes de integração.
 *
 * OpenAPI spec version: beta-0.0.1
 * Contact: suporte-ressarcimento@openbankingbrasil.org.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The RefundNotification model module.
 * @module model/RefundNotification
 * @version beta-0.0.1
 */
export class RefundNotification {
  /**
   * Constructs a new <code>RefundNotification</code>.
   * @alias module:model/RefundNotification
   * @class
   * @param timestamp {String} 
   * @param sessionToken {String} 
   * @param clientId {String} 
   * @param receiverId {String} 
   * @param transmitterId {String} 
   * @param uri {String} 
   * @param statusCode {Number} 
   * @param payloadSize {Number} 
   * @param processTimespan {Number} 
   */
  constructor(timestamp, sessionToken, clientId, receiverId, transmitterId, uri, statusCode, payloadSize, processTimespan) {
    this.timestamp = timestamp;
    this.sessionToken = sessionToken;
    this.clientId = clientId;
    this.receiverId = receiverId;
    this.transmitterId = transmitterId;
    this.uri = uri;
    this.statusCode = statusCode;
    this.payloadSize = payloadSize;
    this.processTimespan = processTimespan;
  }

  /**
   * Constructs a <code>RefundNotification</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RefundNotification} obj Optional instance to populate.
   * @return {module:model/RefundNotification} The populated <code>RefundNotification</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RefundNotification();
      if (data.hasOwnProperty('timestamp'))
        obj.timestamp = ApiClient.convertToType(data['timestamp'], 'String');
      if (data.hasOwnProperty('sessionToken'))
        obj.sessionToken = ApiClient.convertToType(data['sessionToken'], 'String');
      if (data.hasOwnProperty('clientId'))
        obj.clientId = ApiClient.convertToType(data['clientId'], 'String');
      if (data.hasOwnProperty('receiverId'))
        obj.receiverId = ApiClient.convertToType(data['receiverId'], 'String');
      if (data.hasOwnProperty('transmitterId'))
        obj.transmitterId = ApiClient.convertToType(data['transmitterId'], 'String');
      if (data.hasOwnProperty('uri'))
        obj.uri = ApiClient.convertToType(data['uri'], 'String');
      if (data.hasOwnProperty('statusCode'))
        obj.statusCode = ApiClient.convertToType(data['statusCode'], 'Number');
      if (data.hasOwnProperty('payloadSize'))
        obj.payloadSize = ApiClient.convertToType(data['payloadSize'], 'Number');
      if (data.hasOwnProperty('processTimespan'))
        obj.processTimespan = ApiClient.convertToType(data['processTimespan'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} timestamp
 */
RefundNotification.prototype.timestamp = undefined;

/**
 * @member {String} sessionToken
 */
RefundNotification.prototype.sessionToken = undefined;

/**
 * @member {String} clientId
 */
RefundNotification.prototype.clientId = undefined;

/**
 * @member {String} receiverId
 */
RefundNotification.prototype.receiverId = undefined;

/**
 * @member {String} transmitterId
 */
RefundNotification.prototype.transmitterId = undefined;

/**
 * @member {String} uri
 */
RefundNotification.prototype.uri = undefined;

/**
 * @member {Number} statusCode
 */
RefundNotification.prototype.statusCode = undefined;

/**
 * @member {Number} payloadSize
 */
RefundNotification.prototype.payloadSize = undefined;

/**
 * @member {Number} processTimespan
 */
RefundNotification.prototype.processTimespan = undefined;

