/*
 * Plataforma de Ressarcimento do Open Banking Brasil
 * APIs da plataforma de Ressarcimento do Open Banking Brasil para a comunicação online com a plaforma. Através da documentação das APIs abaixo é possível realizar os devidos testes de integração.
 *
 * OpenAPI spec version: beta-0.0.1
 * Contact: suporte-ressarcimento@openbankingbrasil.org.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {RefundNotification} from './model/RefundNotification';
import {RefundProcess} from './model/RefundProcess';
import {RefundAPIV1Api} from './api/RefundAPIV1Api';

/**
* APIs_da_plataforma_de_Ressarcimento_do_Open_Banking_Brasil_para_a_comunicao_online_com_a_plaforma__Atravs_da_documentao_das_APIs_abaixo__possvel_realizar_os_devidos_testes_de_integrao_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var PlataformaDeRessarcimentoDoOpenBankingBrasil = require('index'); // See note below*.
* var xxxSvc = new PlataformaDeRessarcimentoDoOpenBankingBrasil.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new PlataformaDeRessarcimentoDoOpenBankingBrasil.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new PlataformaDeRessarcimentoDoOpenBankingBrasil.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new PlataformaDeRessarcimentoDoOpenBankingBrasil.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version beta-0.0.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The RefundNotification model constructor.
     * @property {module:model/RefundNotification}
     */
    RefundNotification,

    /**
     * The RefundProcess model constructor.
     * @property {module:model/RefundProcess}
     */
    RefundProcess,

    /**
    * The RefundAPIV1Api service constructor.
    * @property {module:api/RefundAPIV1Api}
    */
    RefundAPIV1Api
};
