/*
 * Plataforma de Ressarcimento do Open Banking Brasil
 * APIs da plataforma de Ressarcimento do Open Banking Brasil para a comunicação online com a plaforma. Através da documentação das APIs abaixo é possível realizar os devidos testes de integração.
 *
 * OpenAPI spec version: beta-0.0.1
 * Contact: suporte-ressarcimento@openbankingbrasil.org.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PlataformaDeRessarcimentoDoOpenBankingBrasil);
  }
}(this, function(expect, PlataformaDeRessarcimentoDoOpenBankingBrasil) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('RefundProcess', function() {
      beforeEach(function() {
        instance = new PlataformaDeRessarcimentoDoOpenBankingBrasil.RefundProcess();
      });

      it('should create an instance of RefundProcess', function() {
        // TODO: update the code to test RefundProcess
        expect(instance).to.be.a(PlataformaDeRessarcimentoDoOpenBankingBrasil.RefundProcess);
      });

      it('should have the property processId (base name: "processId")', function() {
        // TODO: update the code to test the property processId
        expect(instance).to.have.property('processId');
        // expect(instance.processId).to.be(expectedValueLiteral);
      });

      it('should have the property status (base name: "status")', function() {
        // TODO: update the code to test the property status
        expect(instance).to.have.property('status');
        // expect(instance.status).to.be(expectedValueLiteral);
      });

    });
  });

}));
