/**
 * Plataforma de Ressarcimento do Open Banking Brasil
 * APIs da plataforma de Ressarcimento do Open Banking Brasil para a comunicação online com a plaforma. Através da documentação das APIs abaixo é possível realizar os devidos testes de integração.
 *
 * OpenAPI spec version: beta-0.0.1
 * Contact: suporte-ressarcimento@openbankingbrasil.org.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param processId 
 * @param status 
 */
data class RefundProcess (

    val processId: kotlin.String? = null,
    val status: RefundProcess.Status? = null
) {
    /**
    * 
    * Values: PENDING,INPROGRESS,PROCCESSED
    */
    enum class Status(val value: kotlin.String){
        PENDING("PENDING"),
        INPROGRESS("IN_PROGRESS"),
        PROCCESSED("PROCCESSED");
    }
}