/**
 * Plataforma de Ressarcimento do Open Banking Brasil
 * APIs da plataforma de Ressarcimento do Open Banking Brasil para a comunicação online com a plaforma. Através da documentação das APIs abaixo é possível realizar os devidos testes de integração.
 *
 * OpenAPI spec version: beta-0.0.1
 * Contact: suporte-ressarcimento@openbankingbrasil.org.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param timestamp 
 * @param sessionToken 
 * @param clientId 
 * @param receiverId 
 * @param transmitterId 
 * @param uri 
 * @param statusCode 
 * @param payloadSize 
 * @param processTimespan 
 */
data class RefundNotification (

    val timestamp: kotlin.String,
    val sessionToken: kotlin.String,
    val clientId: kotlin.String,
    val receiverId: kotlin.String,
    val transmitterId: kotlin.String,
    val uri: kotlin.String,
    val statusCode: kotlin.Int,
    val payloadSize: kotlin.Long,
    val processTimespan: kotlin.Long
) {
}